### ISSUE TITLE
Compile error: Attempted import error: 'registerPlugin' is not exported from '@capacitor/core'.

### ISSUE THREAD

**Issue by msacchetti** [capacitor-community/keep-awake#12]
**Describe the bug**
Attempting to build Ionic React app after importing this plugin.

Failed to compile.
./node_modules/@capacitor-community/keep-awake/dist/esm/index.js
Attempted import error: 'registerPlugin' is not exported from '@capacitor/core'.

@capacitor/core 2.4.0
@Ionic/core 5.5.4
@ionic/react 5.5.4
@capacitor-community/keep-awake 2.2.0

**To Reproduce**

1.  import { KeepAwake } from '@capacitor-community/keep-awake'
2.  add    const keepAwake = async () => { await KeepAwake.keepAwake()}
3. attempt to build

**Desktop (please complete the following information):**

- OS: macOS big sur
- Version 11.1

**Additional context**

**Comment by Boosten** [comment]
@msacchetti make sure you're using version 1 of the plugin with @capacitor/core 2.4.0 since version 2 supports Capacitor 3. Also see the [changelog](https://github.com/capacitor-community/keep-awake/blob/master/CHANGELOG.md#200-2021-04-10)
