### ISSUE TITLE
feat: add `isKeptAwake` method

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/keep-awake#17]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to check if the device is kept awake.

**Describe the solution you'd like**
Add `isKeptAwake` method.

**Describe alternatives you've considered**
No alternative solutions.

**Additional context**

**Comment by jansgescheit** [comment]
@robingenz is there any release date for this feature?

**Comment by robingenz** [comment]
@jansgescheit This feature will be officially released with Capacitor 5 support.

This is an untested development version for Capacitor 4 that you can try:

```
npm i @capacitor-community/keep-awake@3.0.0-dev.a4d5a8d.1683032576
```

**Comment by jansgescheit** [comment]
hmm too bad. I don't necessarily want to upgrade to Capacitor 5 for this feature - since there are no dependencies to Capacitor 5 in my eyes. Then I will solve this somehow differently.

**Comment by robingenz** [comment]
@jansgescheit What is wrong with the dev version? It supports Capacitor 4.

**Comment by jansgescheit** [comment]
@robingenz Probably nothing, but I don't want to use a dev version for production apps. I had been looking forward to this because the readme already praises this feature, but it is not included.
