### ISSUE TITLE
Using keep-awake in react application seems not to be supported.

### ISSUE THREAD

**Issue by jfvilasat** [capacitor-community/keep-awake#18]
Hi.

I'm building a React application that runs on tip of capacitor-ionic. I've added the keep-awake plugin to my react project. I'm using keep-awake version 1.0 due to the version of capacitor i'm using (i'm using version 2.4.7, latest stable).

When i try to keep awake the screen i receive this message in the console: **Line 2 - Msg: KeepAwake does not support web**.

Newer versions of keepawake do support webview applications? Is it a limitation of version 1.0 or there is no way to get this functionalities available to web applications?

Thanks in advance.

**Comment by robingenz** [comment]
Please make sure that the plugin is imported correctly.

Usage example:
```ts
import { Plugins } from '@capacitor/core';

@Component({
  template: `
    <button (click)="keepAwake()">keep awake!</button>
    <button (click)="allowSleep()">let me sleep!</button>
  `,
})
export class AppComponent {
  async keepAwake() {
    await Plugins.KeepAwake.keepAwake();
  }

  async allowSleep() {
    await Plugins.KeepAwake.allowSleep();
  }
}
```

**Comment by jfvilasat** [comment]
I'm sorry robin, I've been out of the office these days.

I've tried your code and it runs like a charm (i've had an error on plugin initialization on my MainActivity), sorry for that and thanks for this good job.
