### ISSUE TITLE
bug: Android Bug import com.getcapacitor.annotation.CapacitorPlugin;

### ISSUE THREAD

**Issue by danielehrhardt** [capacitor-community/keep-awake#19]
![image](https://user-images.githubusercontent.com/19570043/117222513-e2549780-ae0b-11eb-99b0-89cb17d93e0a.png)

import com.getcapacitor.annotation.CapacitorPlugin;

**Comment by robingenz** [comment]
It seems that the plugin was not installed correctly.

Capacitor 3.x:
```bash
npm install @capacitor-community/keep-awake
npx cap sync
```


Capacitor 2.x:
```bash
npm install @capacitor-community/keep-awake@1.0.0
npx cap sync
```

After that, you can synchronize the project with the Gradle files in Android Studio: `File -> Sync Project with Gradle Files`.

A working example can be found here: [robingenz/capacitor-plugin-demo](https://github.com/robingenz/capacitor-plugin-demo)

Please follow the issue template next time!
