### ISSUE TITLE
bug: Android studio does not build with Capacitor 3

### ISSUE THREAD

**Issue by CedNet** [capacitor-community/keep-awake#20]
Now that Capacitor 3 is released I'm attempting to upgrade my app and the only thing my app stalls on is this plugin.

Android studio build fails with:

**_\MainActivity.java:11: error: cannot find symbol
import com.getcapacitor.community.keepawake.KeepAwake;
                                           ^
  symbol:   class KeepAwake
  location: package com.getcapacitor.community.keepawake_**

I'm not smart enough to actually find the bug or suggest a fix.

I'd appreciate if someone can help out how to solve this.

I have installed keep awake ^2.0.0 (found that in another issue)

**Capacitor doctor:**

Latest Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/android: 3.0.0
  @capacitor/ios: 3.0.0

Installed Dependencies:

  @capacitor/cli: 3.0.0
  @capacitor/core: 3.0.0
  @capacitor/ios: 2.4.7
  @capacitor/android: 3.0.0

**Comment by robingenz** [comment]
Please have a look at [Installation](https://github.com/capacitor-community/keep-awake#installation).
You only have to run the follwing commands to install the plugin:
```
npm install @capacitor-community/keep-awake
npx cap sync
```
There is no reason to import the plugin in `MainActivity.java`. Please remove this import.
It should then work.

A working example can be found here: [robingenz/capacitor-plugin-demo](https://github.com/robingenz/capacitor-plugin-demo)

**Comment by CedNet** [comment]
Tried that during upgrade but still got other errors.

I manually removed the import and stuff but the app still failed. Which has nothing to do with this plugin.

For future reference, upgrading to capacitor 3 = delete project and start from scratch. That is what I had to do for the app to fully function as expected.
