### ISSUE TITLE
bug: Does not work

### ISSUE THREAD

**Issue by ironbone** [capacitor-community/keep-awake#23]
I use this plugin with Ionic application on Android
I have only one page. In the class i use

```
ngOnInit() {

    const keepAwake = async () => {

      await KeepAwake.keepAwake();
    };

  }

```
I have tried to call it in different places but alway after 30s the device goes asleep.

**Comment by robingenz** [comment]
Hi @ironbone,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)).
Here you can found a working example that uses this plugin: https://github.com/robingenz/capacitor-plugin-demo

**Comment by ironbone** [comment]
Sorry my error. I have just used - as decribed at your page
```
const keepAwake = async () => {
  await KeepAwake.keepAwake();
};

```
without calling the function keepAwake()
Sorry.

**Comment by robingenz** [comment]
No problem. I assume it works now. For this reason I close this issue.
