### ISSUE TITLE
feat: Indicator whether KeepAwake functionality is supported

### ISSUE THREAD

**Issue by Sirs0ri** [capacitor-community/keep-awake#27]
**Is your feature request related to a problem? Please describe:**

At the moment there seems to be no easy way to determine whether or not the Browser supports KeepAwake without calling it once, and fishing for an exception. It would be handy if the plugin would supply this information.

**Describe the solution you'd like:**

Ideally, KeepAwake would have a boolean-prop that I can read once during the initialisation of my app that tells me whether or not the plugin will work.

**Describe alternatives you've considered:**

My current workaround is to try calling keepAwake() once when my app starts, and see if it throws an error:

```js
import { KeepAwake } from "@capacitor-community/keep-awake"

const KEEP_AWAKE_TEST = KeepAwake.keepAwake()
  .then(() => {
    KeepAwake.allowSleep()
    return true
  })
  .catch((e) => {
    return false
  })

// then, later: 
const keepAwakeAvailable = await KEEP_AWAKE_TEST
if (keepAwakeAvailable ) { /* ... */ }
```

**Additional context:**

n.a.

**Comment by robingenz** [comment]
Hi @Sirs0ri,
thank you for your request.
I created a dev version. You can give it a try:

```
npm i @capacitor-community/keep-awake@2.1.1-dev.0e7ebe7.1657739190
```
