### ISSUE TITLE
hint: Call keepAwake() again after a video was played

### ISSUE THREAD

**Issue by jansgescheit** [capacitor-community/keep-awake#40]
**Plugin version:**
3.0.0

**Platform(s):**

- iOS

**Current behavior:**
Display goes to sleep

**Expected behavior:**
Display keep awake

**Other information:**
I have a strange behaviour which I would not blame on this package but which might be good to know for one or the other.

When I call `await KeepAwake.keepAwake();` the display stays active as expected. But if I then play a video that has audio via a `HTMLVideo` tag, iOS seems to set `UIApplication.shared.isIdleTimerDisabled = false` at the end of the video. 

Hence the hint to call `await KeepAwake.keepAwake();` again after a video has been played.

**Comment by robingenz** [comment]
Thank you for the issue. This is of course a very special case. Unfortunately, I can't think of anything that this plugin could do to work around it. But it's good that others can find this issue now.
