### ISSUE TITLE
Cannot find module '@capacitor-community/keep-awake' or its corresponding type declarations.bug: 

### ISSUE THREAD

**Issue by AEiosApp** [capacitor-community/keep-awake#42]
**Plugin version:**
4.0.0

**Platform(s):**
all, using Capacitor v5 & typescript

**Current behavior:**
Following documentation, for the line:
```
import { KeepAwake } from '@capacitor-community/keep-awake';
```
typescript returns an error:
```
Cannot find module '@capacitor-community/keep-awake' or its corresponding type declarations.
```

<img width="903" alt="Screenshot 2023-11-16 at 10 16 09 AM" src="https://github.com/capacitor-community/keep-awake/assets/19554725/79b1a35a-5b52-4138-9a92-dbe29d01de63">

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/cli: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by AEiosApp** [comment]
Just restarted VSCode and the issue has gone, sorry for the false alarm.
