### ISSUE TITLE
bug: Phone still goes to sleep after using keepAwake() funciton 

### ISSUE THREAD

**Issue by oneStopAiNz** [capacitor-community/keep-awake#43]
**Plugin version:**
@capacitor-community/keep-awake@4.0.0

**Platform(s):**
Android App
Android Web
IOS ( Untested)

**Current behavior:**
The phone still goes to sleep and locks al though I have used the function 
await KeepAwake.keepAwake();

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by oneStopAiNz** [comment]
Thank you for the swift reply I am currently building a test app to reproduce the issue :)

**Comment by oneStopAiNz** [comment]
Thank you for the swift reply , I am creating a test app following the template for you to be able to reproduce the problem 👍

**Comment by oneStopAiNz** [comment]
Hi @robingenz  :) 

After isolating the problem in a repro example I was able to fix the issue, thank you for your time and efforts. I wish you a very happy holiday season. Seems like you are working through some of it as I am XD 
https://github.com/oneStopAiNz/keepAwakeDiagnostic

**Comment by robingenz** [comment]
I'm glad that you figured it out. Happy holidays!
