### ISSUE TITLE
Add support for Capacitor 3

### ISSUE THREAD

**Issue by NunoSav** [capacitor-community/keep-awake#6]
Capacitor 3 requires iOS 12+ and this plugin has 11+.

**Comment by NunoSav** [comment]
I just noticed the following warnings:
>[warn] - Capacitor WebPlugin "KeepAwake" config object was deprecated in v3 and will be removed in v4.
>[warn] - Capacitor plugin "KeepAwake" is using the deprecated "registerWebPlugin()" function

I did not address this issues. Maybe later in another PR.

**Comment by klemensz** [comment]
Can this be merged? (now that Capacitor 3 has a Release Candidate)

**Comment by NunoSav** [comment]
I published my changes under my name to be able to use this. You can find it at https://github.com/NunoSav/no-sleep until @Boosten releases his.

**Comment by klemensz** [comment]
Thanks, I installed your version for now.

**Comment by robingenz** [comment]
`v2.0.0` contains Capacitor 3 support and has been released.
```bash
npm i @capacitor-community/keep-awake@2.0.0
```
